version: "3"

services:    
    mongo:
        container_name: mongo-wateed
        image: mongo:3.6.9
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
volumes:
    mongodata: